# Generated by Django 4.1.3 on 2022-12-12 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=222, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender', 'Gender'), ('do_not_show', 'Do Not Show'), ('male', 'Male'), ('female', 'Female')], max_length=11),
        ),
    ]
