# Generated by Django 4.1.3 on 2022-12-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_vinyl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='record_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.recordlabel'),
            preserve_default=False,
        ),
    ]
