# Generated by Django 4.1.3 on 2022-12-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_vinyl_record_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.style')),
            ],
        ),
    ]
