# Generated by Django 4.1.3 on 2022-12-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_article_image_alter_article_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='artist',
        ),
        migrations.AddField(
            model_name='vinyl',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.artist'),
        ),
    ]
