# Generated by Django 4.1.3 on 2022-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_article_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='article',
            name='headline',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
