# Generated by Django 4.1.3 on 2022-12-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_article_options_article_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/<django.db.models.fields.CharField>'),
        ),
    ]
