# Generated by Django 4.1.3 on 2022-12-19 00:02

from django.db import migrations, models
import final_project.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[final_project.web.validators.age_validator]),
        ),
    ]
