# Generated by Django 4.1.3 on 2022-12-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_artist_image_alter_profile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordlabel',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(null=True, upload_to='styles/'),
        ),
    ]
