# Generated by Django 4.1.3 on 2022-12-21 10:35

import django.core.validators
from django.db import migrations, models
import final_project.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_genre_image_alter_style_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), final_project.web.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender', 'Gender'), ('do_not_show', 'Do Not Show'), ('male', 'Male'), ('female', 'Female')], max_length=11, null=True),
        ),
    ]
