# Generated by Django 4.1.3 on 2022-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
