# Generated by Django 4.1.3 on 2022-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_vinyl_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylpurchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vinylpurchase',
            name='vinyl',
        ),
        migrations.AddField(
            model_name='vinylpurchase',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vinylpurchase',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
