# Generated by Django 4.1.3 on 2022-12-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_purchase_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyl',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
