# Generated by Django 4.1.3 on 2022-12-22 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_vinyl_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1000000)], verbose_name='Price ($)'),
        ),
    ]
